# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: data/partage.yaml
class PartageDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_partage
puts Holidays.between(Date.civil(2013,11,1), Date.civil(2013,11,30), :partage).inspect
{
  Date.civil(2008,1,1) => 'New Year\'s Day', 
  Date.civil(2008,5,26) => 'Memorial Day',
  Date.civil(2008,7,4) => 'Independence Day',
  Date.civil(2008,9,1) => 'Labor Day',
  Date.civil(2013,11,28) => 'Thanksgiving',
  Date.civil(2013,11,29) => 'Black Friday',
  Date.civil(2008,12,25) => 'Christmas Day'
}.each do |date, name|
  assert_equal name, (Holidays.on(date, :partage)[0] || {})[:name]
end

  end
end
