# encoding: utf-8
module Holidays
  # This file is generated by the Ruby Holidays gem.
  #
  # Definitions loaded: data/partage.yaml
  #
  # To use the definitions in this file, load it right after you load the 
  # Holiday gem:
  #
  #   require 'holidays'
  #   require 'holidays/partage'
  #
  # All the definitions are available at https://github.com/alexdunae/holidays
  module PARTAGE # :nodoc:
    def self.defined_regions
      [:partage]
    end

    def self.holidays_by_month
      {
              1 => [{:mday => 1, :observed => lambda { |date| Holidays.to_weekday_if_weekend(date) }, :observed_id => "to_weekday_if_weekend", :name => "New Year's Day", :regions => [:partage]}],
      5 => [{:wday => 1, :week => -1, :name => "Memorial Day", :regions => [:partage]}],
      7 => [{:mday => 4, :observed => lambda { |date| Holidays.to_weekday_if_weekend(date) }, :observed_id => "to_weekday_if_weekend", :name => "Independence Day", :regions => [:partage]}],
      9 => [{:wday => 1, :week => 1, :name => "Labor Day", :regions => [:partage]}],
      11 => [{:wday => 4, :week => 4, :name => "Thanksgiving", :regions => [:partage]},
            {:wday => , :week => 5, :name => "Black Friday", :regions => [:partage]}],
      12 => [{:mday => 25, :observed => lambda { |date| Holidays.to_weekday_if_weekend(date) }, :observed_id => "to_weekday_if_weekend", :name => "Christmas Day", :regions => [:partage]}]
      }
    end
  end


end

Holidays.merge_defs(Holidays::PARTAGE.defined_regions, Holidays::PARTAGE.holidays_by_month)
